version: '3.8'
services:
  client:
    container_name: "client"
    build: client/.
    ports:
      - "3000:3000"
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    environment:
      - CHOKIDAR_USEPOLLING=true