version: "3.8"
services:
  backend:
    container_name: proxy-backend
    build: backend/.
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - 8000:8000
  redis:
    image: redis
    container_name: proxy-db
    ports:
      - 6379:6379
  client:
    container_name: proxy-client
    build: client/.
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
